// generated by build.py — do not edit by hand
const notesSearchEntries = [
  {
    "title": "The Cat in the Box",
    "href": "thorndike-and-the-law-of-effect.html",
    "status": "essay",
    "terms": "learning theory, history of psychology, reinforcement learning Thorndike."
  }
];
