name: Deploy to GitHub Pages
on:
  push:
    branches:
      - new-design
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18" # Updated to a newer version for compatibility
          cache: npm

      - name: Install Dependencies
        run: npm ci # Use `npm ci` for a clean, reproducible install

      - name: Build Project
        run: npm run build && npx next export # Export the project for GitHub Pages

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./out # Update to match the output directory of `next export`

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3